Fix arch detection

diff --git a/uaws b/uaws
--- a/uaws
+++ b/uaws
@@ -3,7 +3,7 @@
 set -eu
 
 arch=
-case $(uname -p) in
+case $(uname -m) in
   x86_64)
     arch=amd64
     ;;
@@ -14,7 +14,7 @@ case $(uname -p) in
     arch=arm64
     ;;
   *)
-    echo "error: unsupported arch" >&2
+    echo "error: unsupported arch $(uname -m)" >&2
     exit 1
     ;;
 esac
@@ -30,7 +30,7 @@ case $(uname -s) in
     ext=.tar.gz
     ;;
   *)
-    echo "error: unsupported OS" >&2
+    echo "error: unsupported OS $(uname -s)" >&2
     exit 1
     ;;
 esac
